/**
 * Generates `src/lib/tickers.generated.ts` — the $TICKER (cashtag) whitelist: the top
 * 1000 CoinStats coins by rank, as an UPPERCASE_SYMBOL → coinId map. The content script
 * uses it both to decide whether a `$CASHTAG` is worth a lookup and to resolve it to a
 * coinId for `/v1/coin` (so a random `$WORD` never hits the Worker).
 *
 * Sort is `rank` ascending — NOT marketCap (verified: `sortBy=marketCap` is broken
 * upstream, it pulls rank-14k/16k coins into the first 1000). On a symbol collision the
 * first (lowest-rank = canonical) coin wins, which keeps scam tokens that reuse a popular
 * ticker out. `limit=1000` is the per-page max and returns the true top-1000 in one call.
 *
 * The output IS committed; run manually to refresh — never in postinstall (needs the key):
 *   COINSTATS_API_KEY=… pnpm --filter @alphapeek/extension tickers:build
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT_FILE = join(__dirname, '..', 'src', 'lib', 'tickers.generated.ts')

const BASE_URL = process.env.COINSTATS_BASE_URL ?? 'https://openapiv1.coinstats.app'
const API_KEY = process.env.COINSTATS_API_KEY
if (!API_KEY) {
  console.error(
    'COINSTATS_API_KEY is required. Run: COINSTATS_API_KEY=… pnpm --filter @alphapeek/extension tickers:build',
  )
  process.exit(1)
}

// The Worker's COINS_CHAIN slug namespace — only used here to report how many whitelist
// coins have a deployment on a chain we support (informational; the map itself is
// chain-agnostic, the Worker derives the safety chain at lookup time).
const SUPPORTED_COINS_SLUGS = new Set([
  'ethereum',
  'binance_smart',
  'polygon-pos',
  'base',
  'arbitrum-one',
  'optimistic-ethereum',
  'avalanche',
])

const url = new URL('/coins', BASE_URL)
url.searchParams.set('limit', '1000')
url.searchParams.set('sortBy', 'rank')
url.searchParams.set('sortDir', 'asc')

const res = await fetch(url, { headers: { 'X-API-KEY': API_KEY, accept: 'application/json' } })
if (!res.ok) {
  console.error(`CoinStats responded ${res.status}`)
  process.exit(1)
}
const body = await res.json()
const coins = Array.isArray(body?.result) ? body.result : []
if (coins.length === 0) {
  console.error('No coins returned — aborting so we never write an empty whitelist.')
  process.exit(1)
}

const tickers = new Map() // UPPER symbol → coinId (first/lowest-rank wins)
let withSupportedContract = 0
for (const coin of coins) {
  const symbol = String(coin?.symbol ?? '').toUpperCase()
  const coinId = String(coin?.id ?? '')
  if (!symbol || !coinId || tickers.has(symbol)) continue
  tickers.set(symbol, coinId)
  const slugs = Array.isArray(coin?.contractAddresses)
    ? coin.contractAddresses.map((e) => e?.blockchain)
    : []
  if (slugs.some((s) => SUPPORTED_COINS_SLUGS.has(s))) withSupportedContract++
}

const q = (s) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
const entries = [...tickers].map(([sym, id]) => `  [${q(sym)}, ${q(id)}],`).join('\n')
const file = `// AUTO-GENERATED by scripts/build-tickers.mjs — DO NOT EDIT BY HAND.
// Top-1000 CoinStats coins by rank → coinId, for $TICKER (cashtag) detection.
// Refresh: \`COINSTATS_API_KEY=… pnpm --filter @alphapeek/extension tickers:build\`
export const TICKERS: ReadonlyMap<string, string> = new Map([
${entries}
])
`

writeFileSync(OUT_FILE, file)
console.info(
  `wrote ${OUT_FILE}: ${tickers.size} symbols from ${coins.length} coins ` +
    `(${withSupportedContract} with a supported-chain contract)`,
)
